import { io as ioClient } from 'socket.io-client';
import prisma from '../db.js';

const BACKEND_URL = process.env.BACKEND_URL || 'http://localhost:3001';
const NUM_CLIENTS = 10;
const NUM_ROUNDS = 5; // 10 clients * 5 rounds = 50 total card move emissions

async function runConcurrencyTest() {
  console.log('==================================================');
  console.log('🧪 Starting FlowMind Socket Concurrency Test Suite');
  console.log(`Backend URL: ${BACKEND_URL}`);
  console.log(`Simulated Users (Connections): ${NUM_CLIENTS}`);
  console.log(`Races Rounds: ${NUM_ROUNDS} (Total of ${NUM_CLIENTS * NUM_ROUNDS} simultaneous moves)`);
  console.log('==================================================');

  // 1. Ensure test board, columns, and card exist
  let board = await prisma.board.findFirst({
    include: { columns: { include: { cards: true } } }
  });

  if (!board) {
    console.log('No boards found. Creating temporary test board workspace...');
    const user = await prisma.user.upsert({
      where: { email: 'test-concurrency@flowmind.com' },
      update: {},
      create: { email: 'test-concurrency@flowmind.com', name: 'Concurrency Tester' }
    });

    board = await prisma.board.create({
      data: {
        name: 'Concurrency Test Board',
        description: 'Autogenerated board for socket stress testing',
        ownerId: user.id,
        columns: {
          create: [
            { name: 'To Do', position: 1000 },
            { name: 'In Progress', position: 2000 }
          ]
        }
      },
      include: { columns: { include: { cards: true } } }
    });
  }

  const columns = board.columns;
  if (columns.length < 2) {
    console.error('Test requires at least 2 columns in the board.');
    process.exit(1);
  }

  const colA = columns[0];
  const colB = columns[1];

  let card = await prisma.card.findFirst({
    where: { boardId: board.id }
  });

  if (!card) {
    console.log('Creating a test card for moves...');
    const user = await prisma.user.findFirst();
    card = await prisma.card.create({
      data: {
        title: 'Concurrency Card',
        description: 'Card subjected to racing websocket update commands',
        position: 1000,
        columnId: colA.id,
        boardId: board.id,
        version: 0,
        userId: user.id
      }
    });
  }

  const testCardId = card.id;
  const testUserId = card.userId || (await prisma.user.findFirst()).id;

  console.log(`Using Board: "${board.name}" (${board.id})`);
  console.log(`Using Card: "${card.title}" (${card.id})`);
  console.log(`Columns: "${colA.name}" (${colA.id}) ↔ "${colB.name}" (${colB.id})`);

  // 2. Connect 10 Socket.io client connections
  const clients = [];
  const connectionPromises = [];

  console.log(`\nConnecting ${NUM_CLIENTS} socket clients...`);
  for (let i = 0; i < NUM_CLIENTS; i++) {
    const socket = ioClient(BACKEND_URL, {
      forceNew: true,
      transports: ['websocket']
    });

    clients.push(socket);

    const connectPromise = new Promise((resolve) => {
      socket.on('connect', () => {
        // Join board room
        socket.emit('join-board', { boardId: board.id });
        resolve(i);
      });
    });
    connectionPromises.push(connectPromise);
  }

  await Promise.all(connectionPromises);
  console.log(`✅ All ${NUM_CLIENTS} socket clients connected and joined room: "board:${board.id}"`);

  // Track results
  let totalSuccess = 0;
  let totalConflicts = 0;
  let totalErrors = 0;

  // Listeners across clients to log callbacks
  clients.forEach((socket, index) => {
    socket.on('card:moved', (data) => {
      if (data.id === testCardId) {
        // This is broadcast to ALL clients when a move succeeds
        // We log successes inside the runner loop
      }
    });

    socket.on('card:move:failed', (res) => {
      if (res.cardId === testCardId) {
        if (res.error && res.error.includes('Conflict')) {
          totalConflicts++;
        } else {
          totalErrors++;
          console.error(`Client ${index} error:`, res.error);
        }
      }
    });
  });

  // 3. Run racing rounds
  for (let round = 1; round <= NUM_ROUNDS; round++) {
    console.log(`\n--- RACE ROUND ${round}/${NUM_ROUNDS} ---`);

    // Fetch the absolute current card state from DB
    const freshCard = await prisma.card.findUnique({
      where: { id: testCardId }
    });

    const currentVersion = freshCard.version;
    const currentColumn = freshCard.columnId;
    // Alternate targets
    const targetColumnId = currentColumn === colA.id ? colB.id : colA.id;
    const targetPosition = freshCard.position + 1.5;

    console.log(`Current Card Version: ${currentVersion} | Column: ${currentColumn === colA.id ? colA.name : colB.name}`);
    console.log(`Targeting Column: ${targetColumnId === colA.id ? colA.name : colB.name}`);
    console.log(`Triggering concurrent emissions from all ${NUM_CLIENTS} clients...`);

    let localSuccessCount = 0;
    
    // Set up a listener for the success broadcast for this round
    const successPromise = new Promise((resolve) => {
      const checkSuccess = (data) => {
        if (data.id === testCardId && data.version === currentVersion + 1) {
          localSuccessCount++;
          // Unregister listener
          clients.forEach(c => c.off('card:moved', checkSuccess));
          resolve();
        }
      };
      clients.forEach(c => c.on('card:moved', checkSuccess));
    });

    // Simultaneously fire card:move updates from all clients
    clients.forEach((socket, clientIndex) => {
      socket.emit('card:move', {
        cardId: testCardId,
        columnId: targetColumnId,
        position: targetPosition,
        version: currentVersion,
        userId: testUserId
      });
    });

    // Wait for the successful broadcast to happen, or timeout (e.g. 1.5s)
    await Promise.race([
      successPromise,
      new Promise(resolve => setTimeout(resolve, 1500))
    ]);

    totalSuccess += localSuccessCount;

    // Small delay to let failures register
    await new Promise(resolve => setTimeout(resolve, 300));
    console.log(`Round Finished: Successful moves broadcasted: ${localSuccessCount} | Total conflict reports accumulated: ${totalConflicts}`);
  }

  // 4. Teardown and Print Report
  console.log('\n==================================================');
  console.log('📊 CONCURRENCY TEST SUMMARY REPORT');
  console.log('==================================================');
  console.log(`Total Moves Emitted:       ${NUM_CLIENTS * NUM_ROUNDS}`);
  console.log(`Successful Updates:        ${totalSuccess} (expected exactly ${NUM_ROUNDS})`);
  console.log(`Conflict Denials Caught:   ${totalConflicts} (expected exactly ${NUM_CLIENTS * NUM_ROUNDS - NUM_ROUNDS})`);
  console.log(`Unresolved Errors:         ${totalErrors} (expected 0)`);
  
  if (totalSuccess === NUM_ROUNDS && totalConflicts === (NUM_CLIENTS * NUM_ROUNDS - NUM_ROUNDS)) {
    console.log('\n🏆 SUCCESS: Concurrency conflict resolution verified!');
    console.log('Last-Write-Wins locks rejected all out-of-date updates.');
  } else {
    console.log('\n⚠️ WARNING: Deviation in expected conflict resolution counts.');
  }
  console.log('==================================================');

  // Disconnect all sockets
  clients.forEach(c => c.disconnect());
  process.exit(0);
}

runConcurrencyTest().catch(err => {
  console.error('Critical test runner crash:', err);
  process.exit(1);
});
